title: Dennis Wu
url: "https://hibb-bb.github.io"
baseurl: "/researcher"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://hibb-bb.github.io"
footer_text: "Dennis Wu"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
