title: Dennis Yu-Hsuan Wu
url: "https://hibb-bb.github.io/"
  # baseurl: "/researcher"

markdown: kramdown
ins_logo: "./logo_nu.png"

tracking_id: #

footer: no
footer_url: "https://hibb-bb.github.io/"
footer_text: "Dennis"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "https://hibb-bb.github.io/"
#  - name: "Resume"
#    link: "resume.pdf"
 - name: "Contact"
   link: "contact"
